import Head from 'next/head'
import { cookies } from 'next/headers'
import { Inter } from 'next/font/google'

import './globals.css'
import Providers from './Providers'
import { AUTH_TOKEN_KEY } from '@/utils/constants'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const cookieStorage = cookies()
  const reqAuthToken = cookieStorage.get(AUTH_TOKEN_KEY)

  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Koulen&display=swap"
        />
      </Head>
      <body className={inter.className}>
        <Providers reqAuthToken={reqAuthToken}>
          {children}
        </Providers>
      </body>
    </html>
  )
}
